### ISSUE TITLE
noise3D(X, Y, Z) seems to use the Z value incorrectly

### ISSUE THREAD

**Issue by Magnogen** [blindman67/SimplexNoiseJS#1]
noise2D(X, Y) works wonderfully, the problem I found is when we start taking slices through the 3rd dimension

When increasing the Z value, it looks like 2D noise, just moving upwards, as opposed to evolving over time.

![SimplexTroubles-longer](https://user-images.githubusercontent.com/25611707/127736709-5fd991d9-f329-41cd-b29e-cc0beaa42843.gif)

And here's the sketch I made to create this, with the SimplexNoiseJS.js code copied straight from here
https://editor.p5js.org/Magnogen/sketches/_KsT29aac

**Comment by blindman67** [comment]
The range for z is 0 to 1. Stepping z by 1 will create the scrolling artifact. Use a smaller step value for z. For example in the linked sketch change `z += 1` to `z += 1 / width`

**Comment by Magnogen** [comment]
Interesting, okay thank you. Why is it not the same as with the other X and Y axes then?

**Comment by blindman67** [comment]
@Magnogen What it does outside the unit square/cube/hypercube is is undefined. This branch uses the source (at time of branching) to define that behavior.
